<?php

namespace AppBundle\Repository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends \Doctrine\ORM\EntityRepository {
    public function getDataCount() {
        return $this->createQueryBuilder('data')
            ->select('COUNT(data.id) as amount')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param array $items
     * @param $max
     * @return array
     */
    public function getRecent(array $items, $max) {
        $query = $this->createQueryBuilder('data')
            ->select()
            ->setMaxResults($max)
            ->orderBy('data.id', 'DESC');

        foreach($items as $item) {
            $query->andWhere('data.'. $item .' IS NOT NULL');
        }

        return $query->getQuery()->getResult();
    }

    public function getMax($max) {
        return $this->createQueryBuilder('data')
            ->select()
            ->setMaxResults($max)
            ->orderBy('data.id', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function getRecentDateTime() {
        return $this->createQueryBuilder('data')
            ->select('data.time, data.date')
            ->setMaxResults(1)
            ->orderBy('data.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
