<?php

namespace AppBundle\Repository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends \Doctrine\ORM\EntityRepository {
    public function getDataCount() {
        return $this->createQueryBuilder('data')
            ->select('COUNT(data.id) as amount')
            ->getQuery()
            ->getResult();
    }

    public function getRecentTemps($max) {
        return $this->createQueryBuilder('data')
            ->select()
            ->setMaxResults($max)
            ->orderBy('data.time', 'ASC')
            ->orderBy('data.date', 'ASC')
            ->where('data.temp IS NOT NULL')
            ->getQuery()
            ->getResult();
    }
}
