# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: AppBundle\Entity\User
                property: mail
        in_memory: { memory: ~ }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout_on_user_change: true
            stateless: false
            form_login:
                login_path: status
                check_path: login
            logout:
                path:   /logout
                target: /
            provider: user_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin*, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_USER : []
        ROLE_ADMIN: [ROLE_USER]
