index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

status:
    path:     /sensors/status
    defaults: { _controller: "AppBundle:Default:status" }

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    prefix:   /admin
    type:     annotation