index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }

status:
    path:     /sensors/status
    defaults: { _controller: "AppBundle:Admin:status" }
    methods:  [GET]

graphData:
    path:     /graph/data
    defaults: { _controller: "AppBundle:Admin:graphData" }

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    prefix:   /admin
    type:     annotation