#easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/AdminController.php'
#    prefix: /admin
#    type: annotation

api_v1:
    resource: "@AppBundle/Resources/config/routing/apiV1.yml"
    prefix:   /api/v1

app:
    resource: "@AppBundle/Resources/config/routing/app.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: "AppBundle:Start:index" }

logout:
    path: /logout
