api_v1:
    resource: "@AppBundle/Resources/config/routing/apiV1.yml"
    prefix:   /api/v1

app:
    resource: "@AppBundle/Resources/config/routing/app.yml"
    prefix:   /

login:
    path:     /login
    defaults: { _controller: "AppBundle:Default:index" }

logout:
    path: /logout
