app_api_v1:
    resource: "@AppBundle/Resources/config/routing/apiV1.yml"
    prefix:   /api/v1

index:
    path:     /
    defaults: { _controller: "AppBundle:Start:index" }

homepage:
    path:     /homepage
    defaults: { _controller: "AppBundle:Default:index" }

login:
    path:     /login
    defaults: { _controller: "AppBundle:Start:index" }

logout:
    path: /logout
