AppBundle\Entity\SensorType:
    type: entity
    repositoryClass: AppBundle\Repository\SensorTypeRepository
    table: sensor_type

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            nullable: false
        description:
            type: string
            nullable: false
        mapping:
            type: text
            nullable: false
        request:
            type: text
            nullable: true